"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Logo } from "@/components/Logo";

export default function SignUpPage() {
  const router = useRouter();
  const [companyName, setCompanyName] = useState("");
  const [adminName, setAdminName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (password !== confirmPassword) {
      alert("Passwords do not match!");
      return;
    }
    setLoading(true);
    // Store registered user session and navigate directly to dashboard home page
    if (typeof window !== "undefined") {
      localStorage.setItem("dayflow_authenticated", "true");
      if (adminName) localStorage.setItem("dayflow_admin_name", adminName);
      if (companyName) localStorage.setItem("dayflow_company_name", companyName);
    }
    setTimeout(() => {
      router.push("/dashboard");
    }, 600);
  };

  return (
    <div className="bg-slate-surface min-h-screen flex items-center justify-center p-gutter-mobile md:p-gutter-desktop antialiased font-sans">
      <div className="w-full max-w-2xl bg-surface-container-lowest rounded-xl border border-border-light flex flex-col md:flex-row overflow-hidden shadow-sm">
        {/* Left Side: Branding / Info (Hidden on Mobile) */}
        <div className="hidden md:flex md:w-5/12 bg-surface-container-low p-space-xl flex-col justify-between border-r border-border-light relative overflow-hidden shrink-0">
          <div className="absolute inset-0 opacity-[0.03]" style={{ backgroundImage: "radial-gradient(#000 1px, transparent 1px)", backgroundSize: "16px 16px" }}></div>
          <div className="relative z-10">
            <div className="mb-space-xxl">
              <Link href="/" className="inline-flex">
                <Logo variant="full" size="md" />
              </Link>
            </div>
            <h2 className="font-headline-lg text-headline-lg text-ink mb-space-md leading-tight">
              Elevate your HR operations.
            </h2>
            <p className="font-body-lg text-body-lg text-secondary">
              Register your company to streamline attendance, time off, and employee management.
            </p>
          </div>

          <div className="relative z-10 bg-surface-container-lowest border border-border-light rounded-lg p-space-md mt-space-xxl flex gap-space-sm items-start shadow-sm">
            <span className="material-symbols-outlined text-secondary" data-weight="fill" style={{ fontVariationSettings: "'FILL' 1" }}>
              info
            </span>
            <div>
              <p className="font-label-md text-label-md text-ink mb-1 font-bold">Employee Onboarding</p>
              <p className="font-body-md text-body-md text-secondary leading-snug">
                Employee accounts are generated by HR/Admin after company registration.
              </p>
            </div>
          </div>
        </div>

        {/* Right Side: Registration Form */}
        <div className="w-full md:w-7/12 p-space-lg md:p-space-xl flex flex-col justify-center bg-surface-container-lowest">
          <div className="mb-space-lg md:hidden flex items-center justify-center gap-2">
            <span className="material-symbols-outlined text-ink text-2xl" data-weight="fill" style={{ fontVariationSettings: "'FILL' 1" }}>
              corporate_fare
            </span>
            <span className="font-headline-md text-headline-md text-ink font-bold tracking-tight">DAYFLOW HRMS</span>
          </div>

          <div className="mb-space-xl">
            <h1 className="font-headline-md text-headline-md text-ink font-bold mb-space-xs">
              Create Company Account
            </h1>
            <p className="font-body-md text-body-md text-secondary">
              Set up your administrator profile.
            </p>
          </div>

          <form className="space-y-space-md" onSubmit={handleSubmit}>
            <div className="space-y-space-md">
              <div>
                <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="companyName">
                  Company Name
                </label>
                <input
                  className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 font-body-md text-body-md text-ink placeholder:text-surface-tint focus:border-ink"
                  id="companyName"
                  placeholder="e.g. Acme Corp"
                  type="text"
                  required
                  value={companyName}
                  onChange={(e) => setCompanyName(e.target.value)}
                />
              </div>

              <div>
                <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold">
                  Company Logo (Optional)
                </label>
                <div className="mt-1 flex justify-center px-6 pt-5 pb-6 border border-border-light border-dashed rounded-lg bg-surface-container-low/50 hover:bg-surface-container-low transition-colors cursor-pointer group">
                  <div className="space-y-1 text-center">
                    <span className="material-symbols-outlined text-secondary text-3xl group-hover:text-ink transition-colors">
                      cloud_upload
                    </span>
                    <div className="flex text-sm text-secondary font-body-md text-body-md justify-center">
                      <span className="relative cursor-pointer bg-transparent rounded-md font-medium text-ink focus-within:outline-none hover:underline">
                        <span>Upload a file</span>
                        <input className="sr-only" id="file-upload" name="file-upload" type="file" />
                      </span>
                      <p className="pl-1">or drag and drop</p>
                    </div>
                    <p className="text-xs text-secondary font-label-sm text-label-sm">
                      PNG, JPG up to 2MB
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <hr className="border-border-light my-space-lg" />

            <div className="space-y-space-md">
              <div>
                <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="adminName">
                  Admin Full Name
                </label>
                <input
                  className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 font-body-md text-body-md text-ink placeholder:text-surface-tint focus:border-ink"
                  id="adminName"
                  placeholder="Jane Doe"
                  type="text"
                  required
                  value={adminName}
                  onChange={(e) => setAdminName(e.target.value)}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md">
                <div>
                  <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="email">
                    Work Email
                  </label>
                  <input
                    className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 font-body-md text-body-md text-ink placeholder:text-surface-tint focus:border-ink"
                    id="email"
                    placeholder="jane@acme.com"
                    type="email"
                    required
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </div>
                <div>
                  <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="phone">
                    Phone Number
                  </label>
                  <input
                    className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 font-body-md text-body-md text-ink placeholder:text-surface-tint focus:border-ink"
                    id="phone"
                    placeholder="+1 (555) 000-0000"
                    type="tel"
                    required
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md">
                <div>
                  <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="password">
                    Password
                  </label>
                  <div className="relative">
                    <input
                      className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 pr-10 font-body-md text-body-md text-ink focus:border-ink"
                      id="password"
                      placeholder="••••••••"
                      type={showPassword ? "text" : "password"}
                      required
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                    />
                    <button
                      className="absolute inset-y-0 right-0 pr-3 flex items-center text-secondary hover:text-ink focus:outline-none cursor-pointer"
                      onClick={() => setShowPassword(!showPassword)}
                      type="button"
                    >
                      <span className="material-symbols-outlined text-lg">
                        {showPassword ? "visibility_off" : "visibility"}
                      </span>
                    </button>
                  </div>
                </div>

                <div>
                  <label className="block font-label-md text-label-md text-ink mb-space-xs font-bold" htmlFor="confirmPassword">
                    Confirm Password
                  </label>
                  <div className="relative">
                    <input
                      className="w-full bg-surface-container-lowest border border-border-light rounded px-3 py-2 pr-10 font-body-md text-body-md text-ink focus:border-ink"
                      id="confirmPassword"
                      placeholder="••••••••"
                      type={showConfirmPassword ? "text" : "password"}
                      required
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                    />
                    <button
                      className="absolute inset-y-0 right-0 pr-3 flex items-center text-secondary hover:text-ink focus:outline-none cursor-pointer"
                      onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      type="button"
                    >
                      <span className="material-symbols-outlined text-lg">
                        {showConfirmPassword ? "visibility_off" : "visibility"}
                      </span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

            <div className="pt-space-md">
              <button
                className="w-full bg-ink text-on-primary font-label-md text-label-md py-3 px-4 rounded hover:bg-primary transition-colors duration-200 active:scale-98 cursor-pointer"
                type="submit"
                disabled={loading}
              >
                {loading ? "Signing up..." : "Sign Up"}
              </button>
            </div>

            <div className="text-center mt-space-md">
              <p className="font-body-md text-body-md text-secondary">
                Already have an account?{" "}
                <Link className="text-ink font-medium hover:underline" href="/signin">
                  Log in
                </Link>
              </p>
            </div>

            <div className="md:hidden mt-space-md bg-surface-container-low border border-border-light rounded p-space-sm flex gap-2 items-start">
              <span className="material-symbols-outlined text-secondary text-sm" data-weight="fill" style={{ fontVariationSettings: "'FILL' 1" }}>
                info
              </span>
              <p className="font-label-sm text-label-sm text-secondary leading-snug">
                Employee accounts are generated by HR/Admin.
              </p>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
