import React from "react";
import { redirect } from "next/navigation";
import { DashboardLayout } from "@/components/DashboardLayout";
import { ProfileTabs } from "@/components/ProfileTabs";
import { getCurrentProfile, getEmployeeByProfileId } from "@/lib/services/employees";

// Tell Next.js to not cache this page dynamically
export const dynamic = "force-dynamic";

export default async function MyProfilePage() {
  // 1. Fetch the authenticated user's profile on the server
  const { profile, error: authError } = await getCurrentProfile();

  if (authError || !profile) {
    redirect("/signin");
  }

  // 2. Fetch the employee details for this profile from the database
  const { employee, error: dbError } = await getEmployeeByProfileId(profile.id);

  // 3. Handle Error State
  if (dbError) {
    return (
      <DashboardLayout>
        <main className="flex-1 w-full">
          <div className="max-w-xl mx-auto px-gutter-mobile md:px-gutter-desktop py-32 text-center">
            <span className="material-symbols-outlined text-danger-text text-5xl mb-4">
              error
            </span>
            <h1 className="font-headline-lg text-headline-lg text-primary font-bold mb-2">
              Failed to load profile
            </h1>
            <p className="text-secondary mb-6 font-body-md">
              There was an issue loading your employee records: {dbError}
            </p>
            <a
              href="/profile"
              className="bg-ink text-on-primary font-label-md text-label-md px-6 py-2.5 rounded hover:bg-primary transition-colors font-bold inline-block"
            >
              Retry Connection
            </a>
          </div>
        </main>
      </DashboardLayout>
    );
  }

  // 4. Handle Empty State (Onboarding Pending)
  if (!employee) {
    return (
      <DashboardLayout>
        <main className="flex-1 w-full">
          <div className="max-w-xl mx-auto px-gutter-mobile md:px-gutter-desktop py-32 text-center">
            <span className="material-symbols-outlined text-secondary text-5xl mb-4 opacity-60">
              hourglass_empty
            </span>
            <h1 className="font-headline-lg text-headline-lg text-primary font-bold mb-2">
              Onboarding Pending
            </h1>
            <p className="text-secondary mb-6 font-body-md leading-relaxed">
              Your profile has been created, but your official employee record has not been generated by the HR department yet. 
              Once HR completes your setup, your dashboard and details will activate automatically.
            </p>
            <div className="text-secondary font-label-sm text-label-sm uppercase tracking-widest bg-surface-container-low py-2 px-4 rounded-lg inline-block">
              Email: {profile.email}
            </div>
          </div>
        </main>
      </DashboardLayout>
    );
  }

  // 5. Render Populated Profile View
  // Server-side Gating: Only HR/Admin see the Salary Info tab DOM structures
  const showSalaryTab = profile.role === "hr" || profile.role === "admin";

  return (
    <DashboardLayout>
      <main className="flex-1 overflow-y-auto w-full">
        <div className="max-w-5xl mx-auto px-gutter-mobile md:px-gutter-desktop py-space-xl">
          {/* Page Header (Profile Snapshot) */}
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-space-lg mb-space-xl">
            <div className="flex items-center gap-space-lg">
              <div className="w-24 h-24 rounded-full overflow-hidden border-2 border-border-light bg-surface-container shadow-sm shrink-0">
                {employee.avatar ? (
                  <img
                    alt="Profile Picture"
                    className="w-full h-full object-cover"
                    src={employee.avatar}
                  />
                ) : (
                  <div className="w-full h-full bg-surface-container-high flex items-center justify-center text-secondary text-4xl font-bold font-sans">
                    {employee.name.split(" ").map(n => n[0]).join("")}
                  </div>
                )}
              </div>
              <div>
                <h1 className="font-headline-lg text-headline-lg text-primary tracking-tight font-bold">
                  {employee.name}
                </h1>
                <p className="font-body-lg text-body-lg text-secondary mt-1">
                  {employee.role} • {employee.department} Department
                </p>
                <div className="flex items-center gap-2 mt-2">
                  <span className={`inline-flex items-center px-2 py-1 rounded font-label-sm text-label-sm font-bold border ${
                    employee.status === "Active" 
                      ? "bg-success-soft text-success-text border-success-text/10" 
                      : employee.status === "Away"
                      ? "bg-warning-soft text-warning-text border-warning-text/10"
                      : "bg-danger-soft text-danger-text border-danger-text/10"
                  }`}>
                    {employee.status}
                  </span>
                  <span className="text-secondary font-label-sm text-label-sm font-bold">
                    {employee.employeeCode}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Profile Tabs & Form content */}
          <ProfileTabs 
            employee={employee} 
            role={profile.role} 
            showSalary={showSalaryTab} 
          />
        </div>
      </main>
    </DashboardLayout>
  );
}
